const messageConstant = {
  passwordNotMatch: "Password & Confirm Password doesnot Match",
  emailAlreadyRegistered: "Email Already Registered",
  newUserCreated: "New User Created Successfully",
  noUserFound: "No User Found with this Email ID",
  noUserFoundWithID: "No User Found with this ID",
  loginSuccess: "Login Successfully",
  invalidToken: "Invalid or Expired Token",
  unauthorizedUser: "Unauthorized User",
  userUpdated: "User Updated Successfully",
  userDeleted: "User Deleted Successfully",
  notLibrarian: "ID does not belongs to Librarian",
  resetLinksend: "An Email with Reset Password link is send to your Email ID",
  passReset: "Password Updated Successfully",
  moveToReset: "Move to Reset Password",
  emailtoActivateAccount:
    "An Email with a Link to Activate Account is Send your Email ID",
  accountActivated: "Your Account is Activated Successfully",
  alreadyDeleted: "User is Already Deleted",
  categoryCreated: "Book Category Created",
  categoryUpdated: "Book Category Updated",
  categoryDeleted: "Book Category Deleted",
  nocategoryFoundwithid: "No Book Category Found With this ID",
  newBookCreated: "New Book Created Successfully",
  BookUpd: "Book Updated Successfully",
  BookDel: "Book Deleted Successfully",
  noBookFound: "No book Exist With this ID",
  LimitExceeded:
    "Cannot Issue New Book Becauese you have Already Issued 5 or more Books",
  newBookIssued: "New Book Issued Successfully",
  outofstock: "Book is out of Stock",
  bookRenewed: "Book Renewed Successfully",
  currentlynotavailable: "Book Currently Not Available",
  Notissued: "User has not issued this Book",
  bookSubmitted: "Book Submitted Successfully",
  bookLost: "Book Lost Request Registered",
  success: "Success",
  fail: "Fail",
  internalServerError: "Internal server error",
  tokenNotFound: "Token Not Found",
  noUserFoundorActive:
    "No User Found with this Email ID or User may be inActive",
};

export default messageConstant;
